
package io.codef.api;

/**
 * <pre>
 * io.codef.easycodef
 *   |_ EasyCodefMessageConstant.java
 * </pre>
 *
 * Desc : EasyCodef에서 사용되는 메시지 코드 클래스 (자동 생성됨)
 * @Company : ©CODEF corp.
 */
public enum EasyCodefMessageConstant {

    SUCCESS("CF-00000", "성공"),
    MISSING_REQUIRED_PARAMETER("CF-00001", "필수 입력 파라미터가 누락되었습니다."),
    INVALID_JSON_FORMAT("CF-00002", "json형식이 올바르지 않습니다."),
    SERVICE_PRODUCT_NOT_FOUND("CF-00003", "요청하신 서비스 상품 정보가 존재하지 않습니다."),
    INVALID_DOMAIN_FOR_DEMO("CF-00004", "요청 도메인이 올바르지 않습니다. 해당 토큰은 데모버전입니다."),
    INVALID_DOMAIN_FOR_PROD("CF-00005", "요청 도메인이 올바르지 않습니다. 해당 토큰은 정식버전입니다."),
    EXCEEDED_REQUEST_LIMIT("CF-00006", "1회 요청 제한 건수를 초과했습니다."),
    INVALID_PARAMETER("CF-00007", "요청 파라미터가 올바르지 않습니다."),
    INVALID_PARAMETER_TYPE("CF-00008", "요청 파라미터의 타입이 올바르지 않습니다."),
    UNSUPPORTED_ENCODING("CF-00009", "지원하지 않는 형식으로 인코딩된 문자열입니다."),
    INVALID_LICENSE("CF-00010", "유효한 라이센스가 아닙니다."),
    NO_AVAILABLE_SERVER("CF-00011", "사용 가능한 정보수집 서버 정보가 없습니다."),
    EXCEEDED_DAILY_LIMIT("CF-00012", "일 100건 요청이 초과되었습니다."),
    UNAUTHORIZED_IP("CF-00013", "요청이 허용된 아이피가 아닙니다."),
    MISSING_CLIENT_INFO("CF-00014", "상품 요청을 위해서는 클라이언트 정보가 필요합니다."),
    MISSING_PUBLIC_KEY("CF-00015", "상품 요청을 위해서는 퍼블릭키가 필요합니다."),
    DUPLICATE_REQUEST("CF-00016", "동일한 요청이 처리되는 중입니다."),
    INVALID_DOMAIN_FOR_SANDBOX("CF-00017", "요청 도메인이 올바르지 않습니다. 해당 토큰은 샌드박스용입니다."),
    OUT_OF_SERVICE_TIME("CF-00018", "서비스 이용 시간이 아닙니다."),
    RESTRICTED_DUE_TO_ABNORMAL("CF-00019", "비정상적인 요청으로 서비스 이용을 제한합니다."),
    SERVICE_SUSPENDED("CF-00020", "서비스가 일시 중지 된 상태입니다."),
    SERVICE_TERMINATED("CF-00021", "종료된 서비스입니다."),
    EXCEEDED_DAILY_PRODUCT_LIMIT("CF-00022", "해당 상품의 일일 요청 가능 건수가 초과되었습니다."),
    BLOCKED_BY_IP_POLICY("CF-00023", "해당 기관은 IP차단 이슈가 있어 일일 요청 건수를 제한합니다."),
    INVALID_ADDITIONAL_AUTH_PARAM("CF-00024", "요청 파라미터가 올바르지 않습니다. 추가인증 입력부를 다시 확인하세요."),
    ALREADY_RESPONDED("CF-00025", "이미 응답이 완료된 요청입니다."),
    INVALID_TOKEN("CF-00026", "유효하지 않은 토큰입니다."),
    BAD_REQUEST("CF-00400", "클라이언트 요청 오류로 인해 요청을 처리 할 수 ​​없습니다."),
    UNAUTHORIZED("CF-00401", "요청 권한이 없습니다."),
    FORBIDDEN("CF-00403", "잘못된 요청입니다."),
    NOT_FOUND("CF-00404", "요청하신 페이지(Resource)를 찾을 수 없습니다."),
    METHOD_NOT_ALLOWED("CF-00405", "요청하신 통신 방법(Method) 잘못되었습니다."),
    INSURANCE_START_DATE_IN_PAST("CF-00901", "보험 시작일은 오늘보다 과거일 수 없습니다."),
    INSURANCE_START_DATE_TOO_FAR("CF-00902", "보험 시작일은 15일을 초과할 수 없습니다."),
    NOT_PARTNER_INSURER("CF-00903", "제휴 보험사가 아닙니다."),
    INVALID_SERVER_INFO("CF-01001", "서버 접속 정보가 부정확합니다."),
    FAILED_SERVER_CONNECTION("CF-01002", "정보수집 서버 접속에 실패했습니다."),
    DATA_TRANSFER_ERROR("CF-01003", "정보 전송 중 오류가 발생했습니다."),
    RESPONSE_TIMEOUT("CF-01004", "응답 대기시간을 초과했습니다."),
    ENGINE_INITIALIZING("CF-01005", "엔진 초기화가 진행중입니다. 잠시 후 다시 시도해주세요."),
    DUPLICATE_LOGIN_RESTRICTED("CF-01006", "중복 로그인 방지를 위해 요청을 제한합니다. 잠시 후 다시 시도해주세요."),
    UNSTABLE_NETWORK("CF-01007", "네트워크 불안정으로 인한 일시적 접속 오류입니다. 잠시 후 다시 시도해 주세요."),
    DATA_SAVE_FAILED("CF-02000", "데이터 저장에 실패했습니다."),
    RESULT_PROCESSING_FAILED("CF-03000", "결과 목록 가공에 실패했습니다."),
    TWO_WAY_INFO_NOT_FOUND("CF-03001", "2WAY 요청 처리를 위한 정보가 존재하지 않습니다."),
    TWO_WAY_PROCESSING_CONTINUE("CF-03002", "API 요청 처리가 정상 진행 중입니다. 추가 정보를 입력하세요."),
    TWO_WAY_PROCESSING_CONTINUE_1("CF-03002", "API 요청 처리가 정상 진행 중입니다. 추가 정보를 입력하세요."), // 중복 코드이지만 식별 위해 구분
    TWO_WAY_INFO_INVALID("CF-03003", "2WAY 요청 처리를 위한 정보가 올바르지 않습니다."),
    REQUEST_CERTIFICATION_REQUIRED("CF-03004", "추가 인증(2Way)을 위한 요청은 requestCertification메서드를 사용해야 합니다."),
    INVALID_PARAMETER_WITH_MESSAGE("CF-03005", "요청 파라미터가 올바르지 않습니다. 추가 메시지를 확인하세요."),
    INVALID_VEHICLE_INFO("CF-03006", "차량 정보가 올바르지 않습니다."),
    REQUEST_PROCESSING_FAILED("CF-03007", "요청이 정상 처리되지 않았습니다. 추가 메세지를 확인하세요."),
    INVALID_AUTH_CODE("CF-03008", "인증코드가 올바르지 않습니다."),
    INVALID_VEHICLE_NUMBER("CF-03009", "유효하지 않는 차량번호입니다."),
    REQUEST_PROCESSING_FAILED_1("CF-03010", "요청이 정상 처리되지 않았습니다. 추가 메세지를 확인하세요."),
    NO_RESULT_FOUND("CF-03999", "조회 결과가 없습니다."),
    ACCOUNT_REGISTRATION_FAILED("CF-04000", "사용자 계정정보 등록에 실패했습니다."),
    THIRD_PARTY_ACCOUNT_SETUP_FAILED("CF-04001", "제3자인증을 위한 계정정보 설정에 실패했습니다."),
    ACCOUNT_SETUP_FAILED("CF-04002", "사용자 계정정보 설정에 실패했습니다."),
    NO_ACCOUNT_TO_REGISTER("CF-04003", "등록할 계정이 없습니다."),
    ACCOUNT_ALREADY_REGISTERED("CF-04004", "이미 계정이 등록된 기관입니다. 기존 계정 먼저 삭제하세요."),
    CLIENT_ID_NOT_FOUND("CF-04005", "client_id가 존재하지 않습니다. 관리자에게 문의하세요."),
    SERVICE_NO_NOT_FOUND("CF-04006", "service_no가 존재하지 않습니다. 관리자에게 문의하세요."),
    PRIVATE_KEY_NOT_FOUND("CF-04007", "비공개키(privateKey)가 존재하지 않습니다."),
    CONNECTED_ID_NOT_FOUND("CF-04008", "커넥티드아이디(connectedId)가 존재하지 않습니다."),
    ACCOUNT_ENCRYPTION_ERROR("CF-04009", "계정 정보 암호화 도중 에러가 발생했습니다."),
    ACCOUNT_UPDATE_FAILED("CF-04010", "사용자 계정정보 수정에 실패했습니다."),
    ACCOUNT_DELETE_FAILED("CF-04011", "사용자 계정정보 삭제에 실패했습니다."),
    ACCOUNT_PARTIAL_SUCCESS("CF-04012", "사용자 계정정보 등록이 부분적으로 성공했습니다."),
    ACCOUNT_QUERY_FAILED("CF-04013", "사용자 계정정보 조회에 실패했습니다."),
    CONNECTED_ID_HAS_NO_ACCOUNT("CF-04014", "요청하신 커넥티드아이디에 연결된 계정이 존재하지 않습니다."),
    NO_ACCOUNT_FOR_CONNECTED_ID("CF-04015", "커넥티드아이디로 찾을 수 있는 기관 계정이 존재하지 않습니다."),
    ACCOUNT_TYPE_MISMATCH("CF-04016", "API 요청 주소와 계정 타입(개인/법인)이 일치하지 않습니다."),
    CLIENT_TYPE_NOT_FOUND("CF-04017", "클라이언트 타입(clientType)이 존재하지 않습니다."),

    CONNECTED_ID_QUERY_FAILED("CF-04018", "커넥티드아이디 조회에 실패했습니다."),
    CONNECTED_ID_NOT_EXIST("CF-04019", "존재하지 않는 커넥티드아이디입니다."),
    PASSWORD_DECRYPTION_FAILED("CF-04020", "비밀번호 복호화에 문제가 발생했습니다."),
    CERT_PFX_DIR_CREATION_FAILED("CF-04021", "인증서 파일(pfx) 변환을 위한 디렉토리 생성에 실패했습니다."),
    CERT_PFX_CREATION_FAILED("CF-04022", "인증서 파일(pfx) 생성에 실패했습니다."),
    CERT_DER_CONVERSION_FAILED("CF-04023", "인증서 파일(der) 변환에 실패했습니다."),
    PFX_FINGERPRINT_EXTRACTION_FAILED("CF-04024", "pfx인증서로부터 핑거프린트 추출에 실패했습니다."),
    PFX_DER_CREATION_FAILED("CF-04025", "pfx인증서로부터 der파일 생성에 실패했습니다."),
    PFX_KEY_CREATION_FAILED("CF-04026", "pfx인증서로부터 key파일 생성에 실패했습니다."),
    PFX_DER_KEY_CREATION_FAILED("CF-04027", "pfx인증서로부터 der,key파일 생성에 실패했습니다."),
    ENCRYPTED_PARAM_CONTAINS_WHITESPACE("CF-04028", "암호화된 파라미터에 공백이 포함되어 있습니다."),
    DUPLICATE_ACCOUNT_IN_REQUEST("CF-04029", "이미 등록된 기관 정보가 존재합니다."),
    REGISTRATION_AND_CERT_REQUIRED("CF-04030", "회원가입 및 인증서 등록이 필요한 기관입니다."),
    ORGANIZATION_NOT_REGISTERED("CF-04031", "등록되지 않은 기관입니다."),
    DUPLICATE_ACCOUNT_EXISTS("CF-04032", "동일한 기관의 계정이 존재합니다."),
    ORGANIZATION_NOT_FOUND("CF-04033", "존재하지 않는 기관입니다."),
    ACCOUNT_REGISTRATION_IN_PROGRESS("CF-04034", "계정 등록이 진행 중입니다."),
    PARTIAL_ADDITIONAL_AUTH_REQUIRED("CF-04035", "추가 인증이 필요한 응답이 일부 존재합니다."),
    IDENTITY_DECRYPTION_FAILED("CF-04036", "identity 복호화에 문제가 발생했습니다."),
    ACCOUNT_DELETE_PARTIAL_SUCCESS("CF-04037", "사용자 계정정보 삭제가 부분적으로 성공했습니다."),
    CONNECTED_ID_ACCOUNT_NOT_FOUND("CF-04038", "커넥티드아이디에 해당 계정이 존재하지 않습니다."),
    API_PROCESSING_ERROR("CF-05001", "API 요청 처리중 오류가 발생하였습니다."),
    IMAGE_BASE64_DECODE_FAILED("CF-05004", "이미지 Base64 복호화에 문제가 발생했습니다."),
    INVALID_FILE_FORMAT("CF-05005", "파일 형식이 올바르지 않습니다."),
    INVALID_ID_CARD_TYPE("CF-05006", "신분증 종류가 올바르지 않습니다."),
    CERT_EXPORT_NOT_STARTED("CF-08000", "인증서 내보내기가 진행되지 않았습니다."),
    CERT_NUMBER_NOT_EXIST("CF-08001", "존재하지 않는 인증번호입니다."),
    CERT_ALREADY_RETRIEVED("CF-08002", "인증서 가져가기가 완료된 인증번호입니다."),
    CERT_RETRIEVE_NOT_STARTED("CF-08003", "인증서 가져가기가 진행되지 않았습니다."),
    TRANSFER_TYPE_NOT_DEFINED("CF-08004", "전송 타입이 정의되지 않았습니다."),
    RELAY_SERVER_UNAUTHORIZED("CF-08005", "코드에프 릴레이 서버 이용 자격이 일치하지 않거나 등록되어 있지 않습니다."),
    INFO_COLLECTION_TYPE_UNDEFINED("CF-09001", "정보수집 타입이 정의되지 않았습니다."),
    ORGANIZATION_INPUT_INVALID("CF-09002", "organization을 올바르게 입력했는지 확인하세요."),
    TWO_WAY_TIMEOUT_UNDEFINED("CF-09003", "2Way 대기 시간이 정의되지 않았습니다."),
    COMMUNICATION_REQUEST_FAILED("CF-09980", "통신 요청에 실패했습니다."),
    COMMUNICATION_ERROR_OCCURRED("CF-09981", "통신 중 오류가 발생했습니다."),
    OAUTH2_TOKEN_ERROR("CF-09990", "OAUTH2.0 토큰 에러입니다."),
    INVALID_OAUTH2_TOKEN("CF-09991", "비정상 OAUTH2.0 토큰입니다."),
    OAUTH2_TOKEN_EXPIRED("CF-09992", "OAUTH2.0 토큰의 사용기간이 지났습니다."),
    OAUTH2_CUSTOMER_INFO_NOT_FOUND("CF-09993", "OAUTH2.0 토큰에 담긴 고객 정보가 존재하지 않습니다."),
    OAUTH2_TOKEN_NOT_EXIST("CF-09994", "OAUTH2.0 토큰이 존재하지 않습니다."),
    UNREGISTERED_ERROR_CODE("CF-09998", "미등록된 에러코드입니다. 관리자에게 문의하세요."),
    SERVER_PROCESSING_ERROR("CF-09999", "서버 처리중 에러가 발생 했습니다. 관리자에게 문의하세요."),
    SUCCESS_1("CF-10000", "성공"),
    LICENSE_CODE_NOT_FOUND("CF-11000", "라이센스 코드가 없습니다."),
    PATH_NOT_SET("CF-11001", "경로가 설정되지 않았습니다."),
    ENGINE_INITIALIZATION_FAILED("CF-11002", "엔진 초기화 실패하였습니다."),
    ENGINE_ALREADY_RUNNING_OR_SUSPENDED("CF-11003", "엔진이 이미 실행 중이거나 서스펜드 상태입니다."),
    ENGINE_STOP_FAILED("CF-11004", "엔진을 중지할 수 없습니다."),
    NO_JOB_TO_EXECUTE("CF-11005", "엔진에 할당된 작업을 실행할 수 없거나 실행할 작업이 없습니다."),
    ENGINE_NOT_RUNNING_CANNOT_SUSPEND("CF-11006", "엔진이 실행 중이지 않기 때문에 서스팬드 할 수 없습니다."),
    ENGINE_NOT_SUSPENDED_CANNOT_RESTART("CF-11007", "엔진이 서스팬드 상태가 아니라 재기동할 수 없습니다."),
    INVALID_JOB_KEY("CF-11008", "작업의 키가 존재하지 않거나 규격에 맞지 않습니다."),
    PATH_NOT_SET_1("CF-11011", "경로가 설정되지 않았습니다."),
    PATH_CREATION_FAILED("CF-11012", "경로를 만들 수가 없습니다."),
    MODULE_PATH_INVALID("CF-11013", "모듈의 경로가 맞지 않습니다."),
    THREAD_CREATION_FAILED("CF-11015", "쓰레드를 생성하지 못하였습니다."),
    EXCEEDED_MAX_JOB_COUNT("CF-11016", "실행 할 수 있는 최대 작업 수를 초과하였습니다."),
    JOB_CREATION_ERROR("CF-11017", "작업 생성 시 오류가 발생하였습니다."),
    MODULE_UPDATE_FAILED("CF-11020", "모듈의 업데이트가 실패하였습니다."),
    REQUEST_PROCESSING_FAILED_WITH_PARAM_CHECK("CF-11021", "요청 처리에 실패했습니다. 요청 주소와 요청 파라미터가 올바른지 확인하세요."),
    UPDATE_TIMEOUT("CF-11022", "업데이트 타임아웃으로 실패하였습니다."),
    UPDATE_SERVER_CONNECTION_FAILED("CF-11023", "업데이트 서버를 연결할 수 없습니다."),
    UPDATE_FILE_CORRUPTED("CF-11024", "업데이트 파일이 손상되었습니다."),
    UUID_NOT_FOUND("CF-11025", "UUID가 존재하지 않습니다."),
    MODULE_FILE_DECRYPTION_FAILED("CF-11031", "모듈의 파일의 복호화 중 오류가 발생하였습니다."),
    FILE_OPEN_ERROR("CF-11032", "파일을 여는 중 오류가 발생하였습니다."),
    FILE_READ_ERROR("CF-11033", "파일을 읽는 도중 오류가 발생하였습니다."),
    MODULE_EXECUTION_ERROR_C("CF-11041", "모듈 실행 중 오류가 발생하였습니다.(C)"),
    MODULE_EXECUTION_ERROR_R("CF-11042", "모듈 실행 중 오류가 발생하였습니다.(R)"),
    INVALID_RESULT_TYPE_STRING("CF-11101", "모듈 실행 결과의 타입(문자열)이 맞지 않습니다."),
    INVALID_ERROR_CODE_TYPE_NUMBER("CF-11102", "에러 코드 타입(숫자)이 맞지 않습니다."),
    INVALID_ERROR_CODE_TYPE_STRING("CF-11103", "에러 코드 타입(문자열)이 맞지 않습니다."),
    INVALID_ERROR_CODE_TYPE_STRING_1("CF-11104", "에러 코드 타입(문자열)이 맞지 않습니다."),
    INVALID_INPUT_PARAM_TYPE_STRING("CF-11105", "입력 파라미터 타입(문자열)이 맞지 않습니다."),
    INVALID_MODULE_CODE_STRUCTURE("CF-11106", "입력된 모듈 코드 체계가 잘못되었습니다."),
    INVALID_SIGNATURE_PARAM("CF-11201", "전자서명의 입력 파라미터가 잘못되었습니다."),
    INVALID_SIGNATURE_PARAM_1("CF-11202", "전자서명의 입력 파라미터가 잘못되었습니다."),
    SIGNATURE_CERTIFICATE_NOT_FOUND("CF-11203", "전자서명 할 인증서가 없습니다."),
    CERT_CONVERSION_ERROR("CF-11204", "인증서 변환 중 오류가 발생하였습니다."),
    CERT_KEY_FILE_NOT_FOUND("CF-11205", "인증서 키파일이 존재하지 않습니다."),
    PKCS_CERT_FORMAT_MISMATCH("CF-11206", "PKCS 인증 형식 미스 매치"),
    PKCS_PRIVATE_KEY_FORMAT_MISMATCH("CF-11207", "PKCS 개인 키 형식 미스 매치"),
    INVALID_RSASSA_PSS_PARAM("CF-11220", "RSAPSS 전자서명의 입력 파라미터가 잘못되었습니다."),
    RSASSA_PSS_PARAM_TYPE_ERROR("CF-11221", "RSAPSS 전자서명 파라미터 데이터 타입 에러"),
    RSASSA_PSS_INPUT_TYPE_MISMATCH("CF-11223", "RSAPSS 전자서명 입력 타입이 맞지 않습니다."),
    INVALID_COMM_PARAM("CF-11301", "통신 송신 데이터의 파라미터가 잘못되었습니다."),
    INVALID_COMM_TYPE_STRING("CF-11302", "통신 송신 데이터의 타입(문자열)이 맞지 않습니다."),
    INVALID_COMM_PARAM_1("CF-11303", "통신 송신 데이터의 파라미터가 잘못되었습니다."),
    INVALID_COMM_TYPE_STRING_1("CF-11304", "통신 송신 데이터의 타입(문자열)이 맞지 않습니다."),
    INVALID_COMM_PARAM_2("CF-11305", "통신 송신 데이터의 파라미터가 잘못되었습니다."),
    INVALID_COMM_TYPE_STRING_2("CF-11306", "통신 송신 데이터의 타입(문자열)이 맞지 않습니다."),
    INVALID_STREAM_PARAM("CF-11401", "스트림 입력 파라미터가 잘못되었습니다."),
    INVALID_STREAM_TYPE("CF-11402", "스트림 입력 타입이 맞지 않습니다."),
    INVALID_HASH_PARAM("CF-11501", "해시 입력 파라미터가 잘못되었습니다."),
    INVALID_HASH_TYPE("CF-11502", "해시 입력 타입이 맞지 않습니다."),
    INVALID_ENCRYPTION_PARAM("CF-11503", "암호화 입력 파라미터가 잘못되었습니다."),
    INVALID_ENCRYPTION_TYPE("CF-11504", "암호화 입력 타입이 맞지 않습니다."),
    INVALID_BASE64_PARAM("CF-11505", "base64 입력 파라미터가 맞지 않습니다."),
    INVALID_BASE64_TYPE("CF-11506", "base64 입력 타입이 맞지 않습니다."),
    DIGEST_INITIALIZATION_ERROR("CF-11507", "다이제스트 초기화 오류입니다."),
    DIGEST_UPDATE_ERROR("CF-11508", "다이제스트 업데이트 오류"),
    INVALID_COMPRESSION_PARAM("CF-11509", "압축 입력 파라미터가 잘못되었습니다."),
    INVALID_COMPRESSION_TYPE("CF-11510", "압축 입력 파라미터 타입이 잘못되었습니다."),
    INVALID_ASN1_PARAM("CF-11601", "ASN1 입력 파라미터가 잘못되었습니다."),
    INVALID_ASN1_TYPE("CF-11602", "ASN1 입력 타입이 맞지 않습니다."),
    UNKNOWN_ERROR_OCCURRED("CF-12000", "알 수 없는 에러가 발생하였습니다."),
    USER_INPUT_TIMEOUT("CF-12001", "사용자 입력 시간이 초과하였습니다. (User Time Out)"),
    INSTITUTION_SERVER_ERROR("CF-12003", "해당 기관 서버에서 오류가 발생하였습니다."),
    SYNTAX_EXCEPTION_OCCURRED("CF-12004", "구문에서 예외가 발생하였습니다."),
    INVALID_INPUT_STRUCTURE("CF-12005", "입력 파라메터 체계가 잘못 되었습니다."),
    NOT_SUPPORTED_IN_THIS_ENGINE_VERSION("CF-12030", "현재 엔진 버전에서는 지원되지 않습니다."),
    NOT_SUPPORTED_IN_THIS_MODULE("CF-12040", "현재 모듈에서 지원되지 않습니다."),
    NOT_AVAILABLE_TIME("CF-12041", "이용 가능 시간이 아닙니다."),
    EXCEEDED_MAX_SEARCH_COUNT("CF-12042", "최대 조회 건수를 초과하였습니다."),
    OUTSTANDING_BALANCE_PREPAYMENT_DENIED("CF-12043", "연체 금액이 있어 선결제가 불가합니다."),
    BANKING_TRANSACTION_RESTRICTED("CF-12044", "사용자 설정으로 인해 뱅킹 거래가 제한된 상태입니다."),
    OVERSEAS_TRANSACTION_RESTRICTED("CF-12045", "해외에서의 거래가 제한된 상태입니다."),
    PREPAYMENT_DENIED_DUE_TO_RESERVED_ACCOUNT("CF-12046", "가상계좌가 예약되어있어 선결제가 불가합니다."),
    RESERVED_VA_PAYMENT_NOT_ALLOWED_SAME_DAY("CF-12047", "결제 당일에는 가상계좌 지정 입금예약이 불가합니다."),
    UNAUTHORIZED_TERMINAL("CF-12048", "현재 접속하신 단말기는 미지정 단말기입니다."),
    NO_VIEW_PERMISSION_FOR_MENU("CF-12049", "해당 메뉴에 조회 권한이 없습니다."),
    SERVICE_NOT_PROVIDED_BY_INSTITUTION("CF-12050", "대상기관에서 제공하지 않는 업무입니다."),
    AGE_RESTRICTED_SERVICE_DENIED("CF-12051", "나이 제한으로 서비스를 이용하실 수 없습니다."),
    ORIGINAL_VERIFIER_REGISTRATION_REQUIRED("CF-12052", "원문대조 확인자 등록이 필요합니다."),
    DATA_LINK_NOT_APPLIED("CF-12053", "정보 연계 신청이 되어있지 않습니다."),
    NOT_YET_ELIGIBLE_FOR_VERIFICATION("CF-12054", "조회 가능일이 지나지 않아 확인이 불가합니다."),
    EXCEEDED_DAILY_ISSUE_LIMIT("CF-12055", "1일 발급 허용횟수가 초과되었습니다."),
    NO_REGISTERED_ACCOUNTS("CF-12056", "조회 계좌로 등록된 계좌가 없습니다."),
    OUTSTANDING_OR_UNPAID_BALANCE("CF-12057", "연체금액 또는 당월대금 결제 후 이용 가능합니다."),
    ACCOUNT_RESTRICTED_BY_INSTITUTION("CF-12058", "대상기관에서 제한된 계정입니다."),
    POSSIBLE_DUPLICATE_WITHDRAWAL("CF-12059", "이중 인출 여부 가능성이 있습니다."),
    OVERDUE_ACCOUNT_EXISTS("CF-12060", "체납 건이 존재합니다."),
    MEDICAL_AID_CANNOT_ISSUE_VERIFICATION("CF-12061", "의료급여세대로 자격확인 발급이 불가합니다."),
    INSUFFICIENT_SUBSCRIPTION_PERIOD("CF-12062", "최소가입기간이 부족하여 연금액을 산정할 수 없습니다."),
    NOT_SUBSCRIBED_TO_RETIREMENT_PLAN("CF-12063", "퇴직연금 미가입 고객입니다."),
    NO_CONTRACT_FOR_CLAIM("CF-12064", "보유계약이 없어 보험금 청구가 불가능합니다."),
    IDENTITY_PROTECTION_SUBSCRIBER("CF-12065", "명의 도용 차단 서비스 가입자입니다."),
    RESIDENT_ID_REQUIRED("CF-12066", "주민등록번호 등록이 필요합니다."),
    INVALID_RESIDENT_ID("CF-12067", "존재하지 않는 주민등록번호입니다."),
    OWN_RESIDENT_ID_NOT_ALLOWED("CF-12068", "본인 주민등록번호는 입력이 불가합니다."),
    DUPLICATE_RESIDENT_ID("CF-12069", "이미 가입된 주민등록번호입니다."),
    PHONE_INFO_NOT_REGISTERED("CF-12070", "등록된 전화번호 정보가 존재하지 않습니다."),
    GUARDIANSHIP_REGISTER_EXISTS("CF-12071", "후견 등기사항이 존재하여 증명서 발급이 불가합니다."),
    HEALTHIN_USER_LINK_FAILED("CF-12072", "건강IN 사용자 연동에 실패하였습니다."),
    PREVIOUS_PASSWORD_NOT_ALLOWED("CF-12073", "변경할 비밀번호로 사용했던 비밀번호는 입력할 수 없습니다."),
    USER_INFO_MISMATCH("CF-12074", "사용자 정보가 일치하지 않습니다."),
    SUBSCRIBER_INFO_NOT_FOUND("CF-12075", "가입자 정보가 없습니다."),
    NO_PUBLIC_PRICE_AVAILABLE("CF-12076", "공시가격이 없습니다."),
    DEVICE_RE_REGISTRATION_REQUIRED("CF-12077", "기기 재등록이 필요합니다."),
    SECURITY_TEXT_REQUIRED("CF-12078", "보안문자 입력이 필요합니다."),
    ALREADY_REGISTERED_INFO("CF-12079", "이미 등록된 정보입니다."),
    PRIVATE_ACCOUNT("CF-12080", "비공개 계정입니다."),
    NO_INSURED_FOR_CLAIM("CF-12090", "청구 가능한 피보험자가 존재하지 않습니다."),
    CONTRACT_NOT_ELIGIBLE_FOR_CLAIM("CF-12091", "보험금 청구가 불가능한 계약입니다."),
    CLAIM_ALREADY_SUBMITTED("CF-12092", "현재 접수되어있는 청구건이 있습니다."),
    UNSUPPORTED_FILE_FORMAT("CF-12093", "지원하지 않는 파일 형식입니다."),
    INVALID_ACCOUNT_INFO("CF-12094", "입력하신 계좌정보가 잘못되었습니다."),
    NO_AUTO_TRANSFER_OR_PAYMENT_ACCOUNT("CF-12095", "자동이체계좌 또는 최근지급계좌가 없습니다."),
    INVALID_PAYOUT_ACCOUNT("CF-12096", "보험금 지급계좌로 선택이 불가능한 계좌입니다."),
    NO_MEDICAL_INSURANCE_FOR_CLAIM("CF-12097", "실손의료보험이 없어 보험금 청구가 불가능합니다."),
    NO_MATCHING_INSURED("CF-12098", "일치하는 피보험자가 없습니다."),
    INSTITUTION_ERROR_MESSAGE_EXISTS("CF-12100", "해당 기관 오류 메시지가 있습니다."),
    ADDITIONAL_AUTH_CANCELLED("CF-12102", "추가 인증 진행이 취소되었습니다."),
    IP_BLOCKED("CF-12103", "IP가 차단되었습니다."),
    TOO_MANY_USERS_TRY_AGAIN_LATER("CF-12104", "접속자 폭주로 접속이 지연되고 있습니다. 잠시 후 다시 시도해주시기 바랍니다."),
    USER_CONFIRMATION_REQUIRED_AGREE_ON_TARGET_SITE("CF-12105", "사용자 확인이 필요합니다. 대상기관 사이트에서 직접 약관동의 등 확인 후 거래하시기 바랍니다."),
    SYSTEM_OVERLOAD_TEMPORARY_RESTRICTION("CF-12106", "과도한 시스템 부하를 방지하고자 일정 시간 이용이 제한됩니다. 나중에 다시 시도 바랍니다."),
    TRANSACTION_DATA_PROCESSING_ERROR_CHANGE_CONDITION("CF-12107", "거래내역 데이터 처리 중 오류가 발생했습니다. 조회 조건을 변경 후 거래하시기 바랍니다. "),
    CARD_POSSESSION_VERIFICATION_REQUIRED_ON_TARGET_SITE("CF-12108", "조회에 실패했습니다. 대상기관 사이트에서 카드소지확인이 필요합니다. 확인 후 거래하시기 바랍니다."),
    NO_RESULT_FOR_GIVEN_QUERY_CONDITIONS("CF-12109", "입력하신 조회 조건에 해당하는 결과가 없습니다."),
    NETWORK_CONNECTION_FAILED_CHECK_AND_RETRY("CF-12200", "통신 연결 실패하였습니다. 네트워크 상태를 확인 후 재시도하시기 바랍니다. "),
    DUPLICATE_LOGIN_DETECTED_ON_ANOTHER_DEVICE("CF-12201", "동일 계정으로 다른 매체에서 로그인하였습니다. 중복 로그인 여부를 확인 후 거래하시기 바랍니다."),
    NETWORK_TIMEOUT_OR_NO_RESPONSE_FROM_TARGET("CF-12202", "통신 연결 시간이 초과하였습니다. 네트워크 상태가 안 좋거나 대상기관에서 응답이 없습니다. 잠시 후 다시 시도하시기 바랍니다."),
    FIREWALL_BLOCKED_COMMUNICATION_CHECK_NETWORK("CF-12203", "방화벽 또는 방화벽 프로그램에 의해 통신 연결이 차단되었습니다. 네트워크 확인 후 거래하시기 바랍니다."),
    IP_CHANGED_SESSION_ENDED_CHECK_NETWORK("CF-12204", "접속정보(IP)가 변경되어 세션이 종료되었습니다. 네트웍 확인 후 거래하시기 바랍니다."),
    INVALID_SESSION("CF-12205", "유효하지 않은 세션입니다."),
    CAPTCHA_OR_BOT_PROTECTION_BLOCKED_REQUEST("CF-12206", "대상 사이트에서 CAPTCHA 또는 유사한 자동화 방지 요소가 감지되어 요청이 차단되었습니다"),
    CERTIFICATE_FILE_NOT_FOUND("CF-12300", "인증서 파일이 없습니다."),
    CERTIFICATE_FILE_PATH_NOT_FOUND("CF-12301", "인증서 파일의 경로를 찾을 수 없습니다."),
    CERTIFICATE_PASSWORD_INCORRECT("CF-12302", "인증서 암호가 틀렸습니다."),
    ELECTRONIC_SIGNATURE_TIME_ERROR("CF-12303", "전자서명 시간 오류가 발생하였습니다."),
    ELECTRONIC_SIGNATURE_DATA_ERROR("CF-12304", "전자서명 데이터 오류입니다."),
    MISSING_LOGIN_OR_SIGNATURE_INFO("CF-12305", "로그인 및 전자서명에 필요 정보가 누락되었습니다."),
    CERTIFICATE_VID_HASHCONTENT_CREATION_ERROR("CF-12306", "공동인증서 VID HashContent 생성 오류"),
    ENCRYPTION_DECRYPTION_ERROR("CF-12307", "암/복호화 도중 오류가 발생하였습니다."),
    DECRYPTION_ERROR("CF-12308", "복호화 도중 오류가 발생하였습니다."),
    LOGIN_PARAMETER_MISSING("CF-12401", "로그인 파라미터가 누락되었습니다."),
    REQUIRED_PARAMETER_MISSING("CF-12411", "필수 파라미터가 누락되었습니다."),
    DATA_CONVERSION_ERROR("CF-12501", "데이터 변환 시 오류가 발생하였습니다."),
    DATA_VALIDATION_ERROR("CF-12502", "데이터 검증시 오류가 발생하였습니다."),
    XML_PARSING_ERROR("CF-12601", "XML 데이터 파싱 오류입니다."),
    XML_ELEMENT_MISSING("CF-12602", "XML 엘리먼트가 없습니다."),
    JSON_DATA_ERROR("CF-12611", "JSON 데이터 오류입니다."),
    DOCUMENT_OR_PAGE_CHANGED("CF-12701", "전문 혹은 페이지가 변경되었습니다."),
    DOCUMENT_OR_DATA_CHANGED("CF-12702", "전문 혹은 데이터가 변경되었습니다."),
    TEMPORARY_ERROR_TRY_AGAIN("CF-12703", "일시적인 오류입니다. 잠시 후 다시 시도해 주세요."),
    SITE_RESTRUCTURING_IN_PROGRESS("CF-12710", "사이트 개편으로 현재 처리 중에 있습니다. "),
    INVALID_ID("CF-12800", "아이디 오류입니다. 확인 후 거래하시기 바랍니다."),
    INVALID_PASSWORD("CF-12801", "비밀번호 오류입니다. 확인 후 거래하시기 바랍니다."),
    PASSWORD_ATTEMPT_LIMIT_EXCEEDED("CF-12802", "비밀번호 오류 횟수 초과입니다. 확인 후 거래하시기 바랍니다."),
    INVALID_ID_OR_PASSWORD("CF-12803", "아이디 또는 비밀번호 오류입니다. 확인 후 거래하시기 바랍니다."),
    IDENTITY_VERIFICATION_MISMATCH("CF-12804", "주민등록번호(사업자번호)와 인증 정보가 일치하지 않습니다. 확인 후 거래하시기 바랍니다."),
    UNREGISTERED_CERTIFICATE("CF-12805", "미등록 인증서입니다. 확인 후 거래하시기 바랍니다."),
    EXPIRED_CERTIFICATE("CF-12806", "만료된 인증서입니다. 확인 후 거래하시기 바랍니다."),
    REVOKED_CERTIFICATE("CF-12807", "폐기된 인증서입니다. 확인 후 거래하시기 바랍니다."),
    EXPIRED_OR_REVOKED_CERTIFICATE("CF-12808", "만료 또는 폐기된 인증서입니다. 확인 후 거래하시기 바랍니다."),
    OTHER_CERTIFICATE_ERROR("CF-12809", "인증서 관련 기타 오류입니다. 확인 후 거래하시기 바랍니다."),
    INVALID_CERTIFICATE_TYPE("CF-12810", "인증서 종류 오류입니다. 확인 후 거래하시기 바랍니다. (개인/기업/용도 제한)"),
    INVALID_BANKING_TYPE("CF-12811", "뱅킹 종류 오류입니다. 확인 후 거래하시기 바랍니다."),
    INTERNET_BANKING_NOT_REGISTERED("CF-12812", "인터넷뱅킹 미가입 고객입니다. 확인 후 거래하시기 바랍니다."),
    UNREGISTERED_OR_REVOKED_CERTIFICATE("CF-12813", "미등록 또는 폐기된 인증서입니다. 확인 후 거래하시기 바랍니다."),
    CANNOT_LOGIN_WITH_PUBLIC_CERTIFICATE("CF-12814", "공인인증서로 로그인이 불가하오니 확인 후 거래하시기 바랍니다."),
    INACTIVE_CUSTOMER("CF-12815", "장기 미사용 고객입니다. 확인 후 거래하시기 바랍니다."),
    TERMINATED_CUSTOMER("CF-12816", "해지된 고객입니다. 확인 후 거래하시기 바랍니다."),
    PASSWORD_NOT_REGISTERED("CF-12817", "비밀번호 미등록 고객입니다. 확인 후 거래하시기 바랍니다."),
    SERVICE_SUSPENDED_CUSTOMER("CF-12818", "이용 중지된 고객입니다. 확인 후 거래하시기 바랍니다."),
    CERTIFICATE_SUSPENDED_PLEASE_RESTORE("CF-12819", "효력 정지된 인증서입니다. 인증서 효력 회복후 이용해주시기 바랍니다."),
    CUSTOMER_ID_ERROR("CF-12820", "Customer ID 오류입니다. 확인 후 거래하시기 바랍니다."),
    OPERATOR_ID_ERROR("CF-12821", "Operator ID 오류입니다. 확인 후 거래하시기 바랍니다."),
    ID_NOT_ENTERED("CF-12822", "ID를 입력하지 않았습니다. 확인 후 거래하시기 바랍니다."),
    PASSWORD_NOT_ENTERED("CF-12823", "비밀번호를 입력하지 않았습니다. 확인 후 거래하시기 바랍니다."),
    INVALID_ID_LENGTH("CF-12824", "아이디 자릿수 오류입니다. 확인 후 거래하시기 바랍니다."),
    INVALID_ID_FORMAT("CF-12825", "아이디 형식 오류입니다. 확인 후 거래하시기 바랍니다."),
    INVALID_PASSWORD_LENGTH("CF-12826", "비밀번호 자릿수 오류입니다. 확인 후 거래하시기 바랍니다."),
    INVALID_PASSWORD_FORMAT("CF-12827", "비밀번호 형식 오류입니다. 확인 후 거래하시기 바랍니다."),
    CERT_PASSWORD_NOT_PROVIDED("CF-12828", "인증서 비밀번호를 입력하지 않았습니다. 확인 후 거래하시기 바랍니다."),
    CERT_FILE_PARAM_MISSING("CF-12829", "인증서 der 파일(reqCertFile) 또는 인증서 key 파일(reqKeyFile) 파라미터 입력값을 입력하지 않았습니다. 확인 후 거래하시기 바랍니다."),
    DAILY_LOGIN_LIMIT_EXCEEDED("CF-12830", "1일 로그인 허용 횟수가 초과하였습니다. 확인 후 거래하시기 바랍니다."),
    AUTHENTICATION_REQUIRED("CF-12831", "본인인증 후 서비스 이용이 가능합니다. 확인 후 거래하시기 바랍니다."),
    WEBSITE_SIGNUP_REQUIRED("CF-12832", "홈페이지 회원가입이 필요합니다. 확인 후 거래하시기 바랍니다."),
    PASSWORD_RESET_REQUIRED("CF-12833", "비밀번호 재설정이 필요합니다. 확인 후 거래하시기 바랍니다."),
    ACCOUNT_UNLOCK_REQUIRED("CF-12834", "계정 잠김 해제가 필요합니다. 확인 후 거래하시기 바랍니다."),
    AUTHENTICATION_PROCESS_FAILED("CF-12835", "본인인증 처리에 실패했습니다. 입력 정보 확인 후 거래하시기 바랍니다."),
    SECURITY_QUESTION_ANSWER_INVALID("CF-12836", "질의에 대한 답변이 잘못 되었습니다. 확인 후 거래하시기 바랍니다."),
    REAL_NAME_VERIFICATION_FAILED("CF-12837", "실명인증에 실패했습니다. 입력한 이름과 주민등록번호를 확인 후 거래하시기 바랍니다."),
    NO_AVAILABLE_FINANCIAL_PRODUCT("CF-12838", "로그인 가능한 금융상품이 없습니다. 확인 후 거래하시기 바랍니다."),
    NO_LOGIN_PERMISSION("CF-12839", "로그인 권한이 없습니다. 확인 후 거래하시기 바랍니다."),
    PIN_PASSWORD_ERROR("CF-12840", "PIN 비밀번호 오류입니다. 확인 후 거래하시기 바랍니다."),
    PIN_PASSWORD_ATTEMPT_EXCEEDED("CF-12841", "PIN 비밀번호 오류 횟수 초과입니다. 확인 후 거래하시기 바랍니다."),
    PIN_PASSWORD_FORMAT_ERROR("CF-12842", "PIN 비밀번호 형식 오류입니다. 확인 후 거래하시기 바랍니다."),
    PIN_PASSWORD_RELATED_ERROR("CF-12843", "PIN 비밀번호 관련 오류입니다. 확인 후 거래하시기 바랍니다."),
    PIN_PASSWORD_NOT_REGISTERED("CF-12844", "PIN 비밀번호가 미등록 되었습니다. 확인 후 거래하시기 바랍니다."),
    PERSONAL_ID_NOT_PROVIDED("CF-12850", "사용자 주민번호/사업자 번호를 입력하지 않았습니다. 확인 후 거래하시기 바랍니다."),
    USER_NAME_NOT_PROVIDED("CF-12851", "사용자 이름을 입력하지 않았습니다. 확인 후 거래하시기 바랍니다."),
    EMPLOYMENT_MGMT_PASSWORD_ERROR("CF-12852", "고용관리/보수관리 비밀번호 오류입니다. 확인 후 거래하시기 바랍니다."),
    TEMP_PASSWORD_ERROR("CF-12853", "임시 비밀번호 오류 입니다. 확인 후 거래하시기 바랍니다."),
    TEMP_PASSWORD_ATTEMPT_EXCEEDED("CF-12854", "임시 비밀번호 오류 횟수 초과 입니다. 확인 후 거래하시기 바랍니다."),
    BIRTHDATE_REQUIRED_AFTER_PASSWORD_FAIL("CF-12855", "특정 횟수 이상 비밀번호를 오입력하여 본인 확인을 위해 생년월일 입력이 필요합니다. 확인 후 거래하시기 바랍니다."),
    CERT_PASSWORD_ATTEMPT_EXCEEDED("CF-12856", "인증서 비밀번호 오류 횟수 초과 입니다. 확인 후 거래하시기 바랍니다."),
    ID_MERGE_REQUIRED("CF-12857", "아이디 통합이 필요합니다. 확인 후 거래하시기 바랍니다."),
    SIGNUP_NOT_ALLOWED("CF-12858", "회원가입이 불가합니다. 확인 후 거래하시기 바랍니다."),
    MULTIPLE_ID_INPUT_REQUIRED("CF-12859", "복수 아이디 사용으로 아이디 입력이 필요합니다. 확인 후 거래하시기 바랍니다."),
    SIMPLE_LOGIN_NOT_CONNECTED("CF-12860", "간편 로그인 수단이 연결되어있지 않습니다. 확인 후 거래하시기 바랍니다."),
    SIMPLE_AUTH_FAILED("CF-12870", "간편인증에 실패했습니다. 앱 설치 또는 인증서 발급 여부를 확인하거나, 사용자 정보(이름, 전화번호, 주민등록번호)를 확인 후 거래하시기 바랍니다."),
    APP_NOT_INSTALLED_OR_CERT_MISSING("CF-12871", "앱이 설치되지 않았거나, 인증서를 발급받지 않으셨습니다. 앱 설치 및 인증서 발급(재발급) 후 거래하시기 바랍니다."),
    AUTH_REQUEST_INCOMPLETE("CF-12872", "인증 요청이 정상적으로 완료되지 않았습니다. 확인 후 거래하시기 바랍니다."),
    AUTH_NOTIFICATION_SETTINGS_REQUIRED("CF-12873", "인증 알림 설정 확인이 필요합니다. 확인 후 거래하시기 바랍니다."),
    CERT_ISSUE_REQUIRED("CF-12874", "인증서 신규 발급이 필요합니다. 확인 후 거래하시기 바랍니다."),
    CHECK_USER_INFO("CF-12875", "사용자 정보를 확인 후 거래하시기 바랍니다."),
    LOGIN_FAILED_TARGET_SITE("CF-12899", "로그인에 실패하였습니다. 대상 기관에서 정상 로그인이 가능한지 확인 후 거래하시기 바랍니다."),
    TRANSFER_EXECUTED_BUT_NO_RESULT("CF-12900", "이체(집금) 실행을 시도하였으나 결과 확인이 불가합니다. 거래내역에서 정상 이체 여부를 반드시 확인하시기 바랍니다."),
    TRANSFER_PERMISSION_ERROR("CF-12901", "이체 권한 관련 오류입니다."),
    TRANSFER_NO_PERMISSION("CF-12902", "이체 권한 없는 사용자입니다. 확인 후 거래하시기 바랍니다. "),
    TRANSFER_INVALID_ACCOUNT("CF-12903", "이체 권한이 없는 계좌번호이거나 출금계좌가 아닙니다. 확인 후 거래하시기 바랍니다."),
    LONG_TERM_NO_TRANSFER("CF-12904", "장기 미이체로 이체가 불가합니다. 확인 후 거래하시기 바랍니다."),
    TRANSFER_INVALID_FEE_ACCOUNT("CF-12905", "이체 권한이 없는 수수료 출금 계좌번호이거나 출금계좌가 아닙니다. 확인 후 거래하시기 바랍니다."),
    DUPLICATE_TRANSFER_SAME_DAY("CF-12906", "동일 일자에 동일 건 송금이 불가합니다. 이체 금액 등을 변경하여 다시 거래하시기 바랍니다."),
    WITHDRAW_ACCOUNT_ERROR("CF-12910", "출금계좌번호 관련 오류입니다."),
    WITHDRAW_ACCOUNT_NOT_PROVIDED("CF-12911", "출금계좌번호를 입력하지 않았습니다. 확인 후 거래하시기 바랍니다."),
    WITHDRAW_ACCOUNT_FORMAT_ERROR("CF-12912", "출금계좌번호 형식 오류 입니다. 확인 후 거래하시기 바랍니다."),
    WITHDRAW_ACCOUNT_UNAVAILABLE_CURRENCY("CF-12913", "입력한 통화코드로는 선택 불가한 출금계좌입니다. 확인 후 거래하시기 바랍니다."),
    WITHDRAW_PASSWORD_ERROR("CF-12920", "출금계좌 비밀번호 오류입니다. 확인 후 거래하시기 바랍니다."),
    WITHDRAW_PASSWORD_ATTEMPT_EXCEEDED("CF-12921", "출금계좌 비밀번호 오류 횟수 초과입니다. 확인 후 거래하시기 바랍니다."),
    WITHDRAW_PASSWORD_FORMAT_ERROR("CF-12922", "출금계좌 비밀번호 형식 오류입니다. 확인 후 거래하시기 바랍니다."),
    WITHDRAW_PASSWORD_RELATED_ERROR("CF-12923", "출금계좌 비밀번호 관련 오류입니다."),
    WITHDRAW_PASSWORD_REPEATED_CHAR("CF-12924", "출금계좌 비밀번호 오류 (같은 숫자/문자)입니다. 확인 후 거래하시기 바랍니다."),
    WITHDRAW_PASSWORD_NOT_PROVIDED("CF-12925", "출금계좌 비밀번호를 입력하지 않았습니다. 확인 후 거래하시기 바랍니다."),
    WITHDRAW_PASSWORD_LENGTH_ERROR("CF-12926", "출금계좌 비밀번호 자릿수 오류입니다. 확인 후 거래하시기 바랍니다."),
    TRANSFER_USER_PASSWORD_ERROR("CF-12930", "이체(이용자) 비밀번호 오류입니다. 확인 후 거래하시기 바랍니다."),
    TRANSFER_USER_PASSWORD_ERROR_COUNT_EXCEEDED("CF-12931", "이체(이용자) 비밀번호 오류 횟수 초과입니다. 확인 후 거래하시기 바랍니다."),
    TRANSFER_USER_PASSWORD_FORMAT_ERROR("CF-12932", "이체(이용자) 비밀번호 형식 오류입니다. 확인 후 거래하시기 바랍니다."),
    TRANSFER_USER_PASSWORD_RELATED_ERROR("CF-12933", "이체(이용자) 비밀번호 관련 오류입니다."),
    TRANSFER_USER_PASSWORD_REPEATED_CHAR("CF-12934", "이체(이용자)비밀번호 오류 (같은 숫자/문자)입니다. 확인 후 거래하시기 바랍니다."),
    TRANSFER_USER_PASSWORD_NOT_PROVIDED("CF-12935", "이체(이용자)비밀번호를 입력하지 않았습니다. 확인 후 거래하시기 바랍니다."),
    TRANSFER_USER_PASSWORD_LENGTH_ERROR("CF-12936", "이체(이용자)비밀번호 자리수 오류입니다. 확인 후 거래하시기 바랍니다."),
    OTP_PASSWORD_ERROR("CF-12940", "OTP 비밀번호 오류입니다. 확인 후 거래하시기 바랍니다."),
    OTP_PASSWORD_ERROR_COUNT_EXCEEDED("CF-12941", "OTP 비밀번호 오류 횟수 초과입니다. 확인 후 거래하시기 바랍니다."),
    OTP_PASSWORD_FORMAT_ERROR("CF-12942", "OTP 비밀번호 형식 오류입니다. 확인 후 거래하시기 바랍니다."),
    OTP_PASSWORD_RELATED_ERROR("CF-12943", "OTP 비밀번호 관련 오류입니다."),
    OTP_DEVICE_ERROR("CF-12944", "OTP 기기 오류입니다. 확인 후 거래하시기 바랍니다."),
    OTP_PASSWORD_NOT_PROVIDED("CF-12945", "OTP 비밀번호를 입력하지 않았습니다. 확인 후 거래하시기 바랍니다."),
    OTP_PASSWORD_LENGTH_ERROR("CF-12946", "OTP 비밀번호 자릿수 오류입니다. 확인 후 거래하시기 바랍니다."),
    OTP_PASSWORD_ALREADY_USED("CF-12947", "이미 사용한 OTP 비밀번호입니다. 확인 후 거래하시기 바랍니다."),
    OTP_CORRECTION_REQUIRED("CF-12948", "OTP 보정거래가 필요합니다. 확인 후 거래하시기 바랍니다."),
    DEPOSIT_ACCOUNT_RELATED_ERROR("CF-12950", "입금계좌 관련 오류입니다. 확인 후 거래하시기 바랍니다."),
    DEPOSIT_BANK_CODE_ERROR("CF-12951", "입금은행(코드) 오류입니다. 확인 후 거래하시기 바랍니다."),
    DEPOSIT_NOT_DESIGNATED_ACCOUNT("CF-12952", "입금지정계좌가 아닙니다. 지정된 계좌로만 입금 가능합니다. 확인 후 거래하시기 바랍니다."),
    DEPOSIT_ACCOUNT_NOT_ALLOWED("CF-12953", "입금 불가 계좌입니다. 확인 후 거래하시기 바랍니다."),
    DEPOSIT_ACCOUNT_TERMINATED("CF-12954", "해지된 입금 계좌입니다. 확인 후 거래하시기 바랍니다."),
    DEPOSIT_ACCOUNT_NOT_PROVIDED("CF-12955", "입금계좌번호를 입력하지 않았습니다. 확인 후 거래하시기 바랍니다."),
    DEPOSIT_ACCOUNT_FORMAT_ERROR("CF-12956", "입금계좌번호 형식 오류 입니다. 확인 후 거래하시기 바랍니다."),
    DEPOSIT_BANK_CODE_NOT_PROVIDED("CF-12957", "입금은행(코드)을 입력하지 않았습니다. 확인 후 거래하시기 바랍니다."),
    DEPOSIT_BANK_CODE_FORMAT_ERROR("CF-12958", "입금은행(코드) 형식 오류 입니다. 확인 후 거래하시기 바랍니다."),
    DEPOSIT_BANK_CODE_LENGTH_ERROR("CF-12959", "입금은행(코드) 자리수 오류입니다. 확인 후 거래하시기 바랍니다."),
    TRANSFER_AMOUNT_RELATED_ERROR("CF-12960", "이체금액 관련 오류입니다. 확인 후 거래하시기 바랍니다."),
    TRANSFER_LIMIT_EXCEEDED_PER_TRANSACTION("CF-12961", "(1회) 한도 초과입니다. 확인 후 거래하시기 바랍니다."),
    TRANSFER_LIMIT_EXCEEDED_PER_DAY("CF-12962", "(1일) 한도 초과입니다. 확인 후 거래하시기 바랍니다."),
    TRANSFER_LIMIT_EXCEEDED_TOTAL("CF-12963", "(전체) 한도 초과입니다. 확인 후 거래하시기 바랍니다."),
    TRANSFER_INSUFFICIENT_BALANCE("CF-12964", "잔액 부족 오류입니다. 확인 후 거래하시기 바랍니다."),
    TRANSFER_LIMIT_EXCEEDED_BOTH("CF-12965", "1회 및 1일 한도 초과입니다. 확인 후 거래하시기 바랍니다."),
    TRANSFER_AMOUNT_EXCEEDS_10_BILLION("CF-12966", "이체 금액이 10억을 초과할 수 없습니다. 금액 조정 후 다시 거래하시기 바랍니다."),
    TRANSFER_AMOUNT_NOT_PROVIDED("CF-12967", "이체금액을 입력하지 않았습니다. 확인 후 거래하시기 바랍니다."),
    TRANSFER_AMOUNT_FORMAT_ERROR("CF-12968", "이체금액 형식 오류 입니다. 확인 후 거래하시기 바랍니다."),
    TRANSFER_AMOUNT_BELOW_MINIMUM("CF-12969", "최소 이체금액이 존재합니다. 이체금액을 확인 바랍니다."),
    WITHDRAW_MEMO_INVALID_CHARACTERS("CF-12970", "출금통장 표시내용에 지원하지 않는 문자가 입력되었습니다. 확인 후 거래하시기 바랍니다."),
    DEPOSIT_MEMO_INVALID_CHARACTERS("CF-12971", "입금통장 표시내용에 지원하지 않는 문자가 입력되었습니다. 확인 후 거래하시기 바랍니다."),
    FEE_ACCOUNT_INSUFFICIENT_BALANCE("CF-12975", "수수료 출금계좌 잔액 부족 오류입니다. 확인 후 거래하시기 바랍니다."),
    FEE_ACCOUNT_RELATED_ERROR("CF-12976", "수수료 출금계좌 관련 오류입니다."),
    FEE_ACCOUNT_NOT_PROVIDED("CF-12977", "수수료 출금계좌번호를 입력하지 않았습니다. 확인 후 거래하시기 바랍니다."),
    WITHDRAW_ACCOUNT_NUMBER_FORMAT_ERROR("CF-12978", "출금계좌번호 형식 오류 입니다. 확인 후 거래하시기 바랍니다."),
    UNSELECTABLE_FEE_WITHDRAW_ACCOUNT_NUMBER("CF-12979", "선택 불가능한 수수료 출금계좌번호입니다. 확인 후 거래하시기 바랍니다."),
    FEE_WITHDRAW_ACCOUNT_PASSWORD_ERROR("CF-12980", "수수료 출금계좌 비밀번호 오류입니다. 확인 후 거래하시기 바랍니다."),
    FEE_WITHDRAW_ACCOUNT_PASSWORD_ERROR_COUNT_EXCEEDED("CF-12981", "수수료 출금계좌 비밀번호 오류 횟수 초과 입니다. 확인 후 거래하시기 바랍니다."),
    FEE_WITHDRAW_ACCOUNT_PASSWORD_FORMAT_ERROR("CF-12982", "수수료 출금계좌 비밀번호 형식 오류 입니다. 확인 후 거래하시기 바랍니다."),
    FEE_WITHDRAW_ACCOUNT_PASSWORD_RELATED_ERROR("CF-12983", "수수료 출금계좌 비밀번호 관련 오류입니다."),
    FEE_WITHDRAW_ACCOUNT_PASSWORD_REPEATED_CHAR("CF-12984", "수수료 출금계좌 비밀번호 오류 (같은 숫자/문자)입니다. 확인 후 거래하시기 바랍니다."),
    FEE_WITHDRAW_ACCOUNT_PASSWORD_NOT_PROVIDED("CF-12985", "수수료 출금계좌 비밀번호를 입력하지 않았습니다. 확인 후 거래하시기 바랍니다."),
    FEE_WITHDRAW_ACCOUNT_PASSWORD_LENGTH_ERROR("CF-12986", "수수료 출금계좌 비밀번호 자리수 오류입니다. 확인 후 거래하시기 바랍니다."),
    INVALID_BUSINESS_OR_RESIDENT_NUMBER("CF-13000", "사업자번호(주민등록번호)가 잘못되었습니다. 확인 후 거래하시기 바랍니다."),
    QUERY_DATE_OR_PERIOD_CHECK_ERROR("CF-13001", "조회일 혹은 기간 체크 오류입니다. 확인 후 거래하시기 바랍니다."),
    INVALID_PARAMETER_ERROR("CF-13002", "잘못된 파라미터 오류입니다. 확인 후 거래하시기 바랍니다."),
    ADDITIONAL_INFO_INVALID_2WAY("CF-13003", "추가 정보 입력값이 잘못되었습니다. (2way) 확인 후 거래하시기 바랍니다."),
    DUPLICATE_CARD_IN_LIST("CF-13004", "카드번호 리스트에서 마스킹을 제외한 번호가 동일한 카드가 하나 이상입니다. 확인 후 거래하시기 바랍니다."),
    INVALID_BIRTHDATE("CF-13005", "생년월일이 잘못되었습니다. 확인 후 거래하시기 바랍니다."),
    NO_SEARCH_RESULTS("CF-13006", "검색결과가 없습니다. 검색어에 잘못된 철자가 없는지, 정확한 주소인지 다시 한번 확인해 주세요."),
    TOO_MANY_SEARCH_RESULTS("CF-13007", "검색결과가 너무 많습니다. 주소를 상세히 입력해 주시기 바랍니다."),
    NO_INFO_FOR_ADDRESS("CF-13008", "해당 주소에 대한 정보가 없습니다. 주소 입력값 수정 후 재시도 하시기 바랍니다."),
    TERMINATED_ACCOUNT("CF-13010", "해지된 계좌입니다. 확인 후 거래하시기 바랍니다."),
    UNREGISTERED_FAST_VIEW_ACCOUNT("CF-13011", "빠른 조회 서비스 미등록 계좌입니다. 빠른 조회 서비스 등록 후 거래하시기 바랍니다."),
    DORMANT_ACCOUNT("CF-13012", "휴면 계좌입니다. 확인 후 거래하시기 바랍니다."),
    NON_EXISTENT_ACCOUNT_NUMBER("CF-13013", "존재하지 않는 계좌번호입니다. 확인 후 거래하시기 바랍니다."),
    UNAVAILABLE_ACCOUNT("CF-13014", "거래가 불가능한 계좌입니다. 확인 후 거래하시기 바랍니다."),
    VIRTUAL_ACCOUNT_QUERY_ERROR("CF-13016", "가상계좌 조회 중 오류가 발생하였습니다."),
    MISMATCH_ID_AND_ACCOUNT_HOLDER("CF-13017", "주민/사업자번호와 출금계좌 예금주 정보가 일치하지 않습니다. 확인 후 거래하시기 바랍니다."),
    VIRTUAL_ACCOUNT_ALREADY_EXISTS("CF-13018", "이미 존재하는 가상계좌번호입니다. 확인 후 거래하시기 바랍니다."),
    VIRTUAL_ACCOUNT_NOT_AVAILABLE("CF-13019", "사용불가한 가상계좌입니다. 확인 후 거래하시기 바랍니다."),
    ACCOUNT_NUMBER_NOT_PROVIDED("CF-13020", "계좌번호를 입력하지 않았습니다. 확인 후 거래하시기 바랍니다."),
    NO_MATCHING_ACCOUNT_IN_LIST("CF-13021", "계좌번호 List에 입력된 계좌번호와 일치하는 정보가 없습니다. 보유계좌 여부를 확인 후 거래하시기 바랍니다.​"),
    ACCOUNT_NUMBER_RELATED_ERROR("CF-13022", "계좌번호 관련 오류입니다. 확인 후 거래하시기 바랍니다."),
    ACCOUNT_NUMBER_LENGTH_ERROR("CF-13023", "계좌번호 자리수 오류입니다. 확인 후 거래하시기 바랍니다.​"),
    ACCOUNT_NUMBER_FORMAT_ERROR("CF-13024", "계좌번호 형식 오류입니다. 확인 후 거래하시기 바랍니다."),
    NO_AVAILABLE_ACCOUNT("CF-13025", "조회 가능한 계좌가 없습니다. 보유계좌 여부를 확인 후 거래하시기 바랍니다.​"),
    ACCOUNT_PASSWORD_NOT_PROVIDED("CF-13030", "계좌 비밀번호를 입력하지 않았습니다. 확인 후 거래하시기 바랍니다."),
    ACCOUNT_PASSWORD_ERROR("CF-13031", "계좌 비밀번호 오류입니다. 확인 후 거래하시기 바랍니다."),
    ACCOUNT_PASSWORD_ERROR_COUNT_EXCEEDED("CF-13032", "계좌 비밀번호 오류 횟수 초과입니다. 확인 후 거래하시기 바랍니다."),
    ACCOUNT_PASSWORD_FORMAT_ERROR("CF-13033", "계좌 비밀번호 형식 오류입니다. 확인 후 거래하시기 바랍니다."),
    ACCOUNT_PASSWORD_LENGTH_ERROR("CF-13034", "계좌 비밀번호 자릿수 오류입니다. 확인 후 거래하시기 바랍니다."),
    ACCOUNT_PASSWORD_RELATED_ERROR("CF-13035", "계좌 비밀번호 관련 오류입니다. 확인 후 거래하시기 바랍니다."),
    CURRENCY_CODE_NOT_PROVIDED("CF-13040", "통화코드를 입력하지 않았습니다. 확인 후 거래하시기 바랍니다."),
    CURRENCY_CODE_NO_MATCHING_INFO("CF-13041", "입력된 통화코드와 일치하는 정보가 없습니다. 확인 후 거래하시기 바랍니다."),
    CURRENCY_CODE_RELATED_ERROR("CF-13042", "통화코드 관련 오류입니다. 확인 후 거래하시기 바랍니다."),
    RETIREMENT_PLAN_TYPE_NOT_PROVIDED("CF-13045", "퇴직연금 제도 구분을 입력하지 않았습니다. 확인 후 거래하시기 바랍니다."),
    RETIREMENT_PLAN_TYPE_MISMATCH("CF-13046", "퇴직연금 제도 구분이 일치하지 않습니다. 확인 후 거래하시기 바랍니다."),
    INVALID_BUSINESS_REGISTRATION_NUMBER("CF-13048", "유효하지 않은 사업자등록번호입니다. 확인 후 거래하시기 바랍니다."),
    NO_MATCHING_BUSINESS_REGISTRATION_NUMBER("CF-13049", "일치하는 사업자등록번호가 없습니다. 확인 후 거래하시기 바랍니다."),
    PRODUCT_CODE_NOT_PROVIDED("CF-13050", "상품코드를 입력하지 않았습니다. 확인 후 거래하시기 바랍니다."),
    INVALID_PRODUCT_CODE("CF-13051", "없는 상품코드입니다. 확인 후 거래하시기 바랍니다."),
    BUSINESS_PLACE_CODE_NOT_PROVIDED("CF-13052", "사업장명 코드를 입력하지 않았습니다. 확인 후 거래하시기 바랍니다."),
    NO_MATCHING_BUSINESS_PLACE_CODE("CF-13053", "일치하는 사업장명 코드가 없습니다. 확인 후 거래하시기 바랍니다."),
    NO_AVAILABLE_BUSINESS_PLACE_CODE("CF-13054", "조회가능한 사업장명 코드가 없습니다. 확인 후 거래하시기 바랍니다."),
    NO_BUSINESS_INFO_FOUND("CF-13058", "사업장 정보를 찾을 수 없습니다. 확인 후 거래하시기 바랍니다."),
    NO_BUSINESS_OPEN_INFO_FOUND("CF-13059", "사업개시 정보를 찾을 수 없습니다. 확인 후 거래하시기 바랍니다."),
    BIRTHDATE_NOT_PROVIDED("CF-13060", "생년월일을 입력하지 않았습니다. 확인 후 거래하시기 바랍니다.​"),
    BIRTHDATE_MISMATCH("CF-13061", "생년월일 정보가 일치하지 않습니다. 확인 후 거래하시기 바랍니다."),
    BIRTHDATE_FORMAT_ERROR("CF-13062", "생년월일 형식 오류입니다. 확인 후 거래하시기 바랍니다.​"),
    BIRTHDATE_LENGTH_ERROR("CF-13063", "생년월일 자리수 오류입니다. 확인 후 거래하시기 바랍니다.​"),
    BIRTHDATE_RELATED_ERROR("CF-13064", "생년월일 관련 오류입니다. 확인 후 거래하시기 바랍니다.​"),
    CARD_NUMBER_NOT_PROVIDED("CF-13100", "카드번호를 입력하지 않았습니다. 확인 후 거래하시기 바랍니다."),
    NO_MATCHING_CARD_IN_LIST("CF-13101", "카드번호 List에 입력된 카드번호와 일치하는 정보가 없습니다. 카드 상태 및 보유카드 여부를 확인 후 거래하시기 바랍니다."),
    CARD_NUMBER_RELATED_ERROR("CF-13102", "카드번호 관련 오류입니다. 확인 후 거래하시기 바랍니다."),
    CARD_NUMBER_INPUT_ERROR("CF-13103", "카드번호를 잘못 입력하셨습니다. 확인 후 다시 거래하시기 바랍니다."),
    CARD_NUMBER_FORMAT_ERROR("CF-13104", "카드번호 형식 오류입니다. 확인 후 거래하시기 바랍니다."),
    NO_AVAILABLE_CARD("CF-13105", "조회 가능한 카드가 없습니다. 카드 상태 및 보유카드 여부를 확인 후 거래하시기 바랍니다.​"),
    TOO_MANY_CARDS_FOUND("CF-13106", "조회된 카드가 너무 많습니다. 상세한 조건을 입력해 주시기 바랍니다."),
    CARD_SUSPENDED("CF-13110", "사용정지된 카드입니다. 확인 후 거래하시기 바랍니다."),
    CARD_PASSWORD_NOT_PROVIDED("CF-13120", "카드 비밀번호를 입력하지 않았습니다. 확인 후 거래하시기 바랍니다."),
    CARD_PASSWORD_ERROR("CF-13121", "카드 비밀번호 오류입니다. 확인 후 거래하시기 바랍니다."),
    CARD_PASSWORD_ERROR_COUNT_EXCEEDED("CF-13122", "카드 비밀번호 오류 횟수 초과입니다. 확인 후 거래하시기 바랍니다."),
    CARD_PASSWORD_FORMAT_ERROR("CF-13123", "카드 비밀번호 형식 오류입니다. 확인 후 거래하시기 바랍니다."),
    CARD_PASSWORD_LENGTH_ERROR("CF-13124", "카드 비밀번호 자릿수 오류입니다. 확인 후 거래하시기 바랍니다."),
    CARD_PASSWORD_RELATED_ERROR("CF-13125", "카드 비밀번호 관련 오류입니다. 확인 후 거래하시기 바랍니다."),
    CARD_CVC_NOT_PROVIDED("CF-13130", "카드 CVC번호를 입력하지 않았습니다. 확인 후 거래하시기 바랍니다."),
    CARD_CVC_ERROR("CF-13131", "카드 CVC번호 오류입니다. 확인 후 거래하시기 바랍니다."),
    CARD_CVC_ERROR_COUNT_EXCEEDED("CF-13132", "카드 CVC번호 오류 횟수 초과입니다. 확인 후 거래하시기 바랍니다."),
    CARD_CVC_FORMAT_ERROR("CF-13133", "카드 CVC번호 형식 오류입니다. 확인 후 거래하시기 바랍니다."),
    CARD_CVC_LENGTH_ERROR("CF-13134", "카드 CVC번호 자릿수 오류입니다. 확인 후 거래하시기 바랍니다."),
    CARD_CVC_RELATED_ERROR("CF-13135", "카드 CVC번호 관련 오류입니다. 확인 후 거래하시기 바랍니다."),
    CARD_EXPIRY_NOT_PROVIDED("CF-13140", "카드 유효기간을 입력하지 않았습니다. 확인 후 거래하시기 바랍니다."),
    CARD_EXPIRY_ERROR("CF-13141", "카드 유효기간 오류입니다. 확인 후 거래하시기 바랍니다."),
    CARD_EXPIRY_ERROR_COUNT_EXCEEDED("CF-13142", "카드 유효기간 오류 횟수 초과입니다. 확인 후 거래하시기 바랍니다."),
    CARD_EXPIRY_FORMAT_ERROR("CF-13143", "카드 유효기간 형식 오류입니다. 확인 후 거래하시기 바랍니다."),
    CARD_EXPIRY_LENGTH_ERROR("CF-13144", "카드 유효기간 자리수 오류입니다. 확인 후 거래하시기 바랍니다."),
    CARD_EXPIRY_RELATED_ERROR("CF-13145", "카드 유효기간 관련 오류입니다. 확인 후 거래하시기 바랍니다."),
    PHONE_NUMBER_NOT_PROVIDED("CF-13150", "전화번호를 입력하지 않았습니다. 확인 후 거래하시기 바랍니다."),
    PHONE_NUMBER_FORMAT_ERROR("CF-13151", "전화번호 형식 오류입니다. 확인 후 거래하시기 바랍니다."),
    PHONE_NUMBER_LENGTH_ERROR("CF-13152", "전화번호 자리수 오류입니다. 확인 후 거래하시기 바랍니다."),
    PHONE_NUMBER_RELATED_ERROR("CF-13153", "전화번호 관련 오류입니다. 확인 후 거래하시기 바랍니다."),
    PHONE_NUMBER_MISMATCH("CF-13154", "등록된 전화번호와 일치하지 않습니다. 확인 후 거래하시기 바랍니다."),
    REMITTER_NAME_EN_NOT_PROVIDED("CF-13155", "송금인 영문 이름을 입력하지 않았습니다. 확인 후 거래하시기 바랍니다."),
    REMITTER_NAME_EN_FORMAT_ERROR("CF-13156", "송금인 영문 이름 형식 오류입니다. 확인 후 거래하시기 바랍니다."),
    REMITTER_NAME_EN_RELATED_ERROR("CF-13157", "송금인 영문 이름 관련 오류입니다. 확인 후 거래하시기 바랍니다."),
    ADDRESS_NOT_PROVIDED("CF-13160", "주소를 입력하지 않았습니다. 확인 후 거래하시기 바랍니다."),
    ADDRESS1_NOT_PROVIDED("CF-13161", "주소1을 입력하지 않았습니다. 확인 후 거래하시기 바랍니다."),
    ADDRESS_FORMAT_ERROR("CF-13162", "주소 형식 오류입니다. 확인 후 거래하시기 바랍니다."),
    ADDRESS1_FORMAT_ERROR("CF-13163", "주소1 형식 오류입니다. 확인 후 거래하시기 바랍니다."),
    ADDRESS_REGISTRATION_REQUIRED("CF-13164", "주소 등록이 필요합니다. 확인 후 거래하시기 바랍니다."),
    RECIPIENT_NOT_PROVIDED("CF-13165", "수취인을 입력하지 않았습니다. 확인 후 거래하시기 바랍니다."),
    RECIPIENT_FORMAT_ERROR("CF-13166", "수취인 형식 오류입니다. 확인 후 거래하시기 바랍니다."),
    RECIPIENT_RELATED_ERROR("CF-13167", "수취인 관련 오류입니다. 확인 후 거래하시기 바랍니다."),
    CAR_NUMBER_OR_VIN_NOT_PROVIDED("CF-13220", "차량번호(차대번호)를 입력하지 않았습니다. 확인 후 거래하시기 바랍니다."),
    NO_OWNERSHIP_INFO_FOR_CAR_NUMBER("CF-13221", "입력된 차량번호와 일치하는 소유차량정보가 없습니다. 확인 후 거래하시기 바랍니다."),
    CONTACT_INSURANCE_CALL_CENTER("CF-13222", "해당 건은 보험사 콜센터로 연락주시기 바랍니다. {*보험료 계산 불가*}"),
    ONLY_CARS_WITHIN_30_DAYS_OF_EXPIRY_CAN_BE_QUERIED("CF-13223", "자동차보험 만기일 30일내인 차량만 조회가 가능합니다. 확인 후 거래하시기 바랍니다."),
    LIMITED_QUERY_IF_GAP_LESS_THAN_3_YEARS("CF-13224", "과거계약 종료시점과 신규가입시점의 공백이 3년 이내인 경우 보험다모아에서 조회가 제한됩니다. 확인 후 거래하시기 바랍니다."),
    NON_EXISTENT_CAR_NUMBER_OR_VIN("CF-13225", "존재하지 않는 차량번호(차대번호)입니다. 확인 후 거래하시기 바랍니다."),
    NO_INSURANCE_INFO_AT_KIDI("CF-13226", "보험개발원에서 조회되는 보험가입정보가 없습니다."),
    UNAVAILABLE_CAR_INFO_FROM_ORGANIZATION("CF-13227", "해당 기관에서 조회가 불가능한 차량정보입니다. 확인 후 거래하시기 바랍니다."),
    COMMERCIAL_CAR_INSURANCE_NOT_AVAILABLE("CF-13228", "영업용 차량은 보험료 계산이 불가합니다. 확인 후 거래하시기 바랍니다."),
    PREMIER_PLAN_REQUIRES_AT_LEAST_ONE_OPTIONAL_COVERAGE("CF-13229", "프리미어 플랜은 부가담보 1개이상 가입하여야 합니다. 확인 후 거래하시기 바랍니다."),
    CAR_OWNER_NAME_MISMATCH("CF-13230", "입력된 차량번호와 소유자명이 일치하지 않습니다. 확인 후 거래하시기 바랍니다."),
    UNAVAILABLE_CAR_REGISTRATION_SUB("CF-13231", "자동차등록원부 을부를 발급할 수 없는 차량입니다. 확인 후 거래하시기 바랍니다."),
    ALREADY_RENEWED_INSURANCE("CF-13232", "이미 자동차보험 갱신이 완료되어 보험료 계산이 불가합니다. 확인 후 거래하시기 바랍니다."),
    OWNED_CAR_VIN_CALCULATION_NOT_ALLOWED("CF-13233", "본인 소유 차량은 차량/차대번호를 입력하여 보험료 계산이 불가합니다. 확인 후 거래하시기 바랍니다."),
    CANCELLED_CAR("CF-13234", "말소된 차량입니다. 확인 후 거래하시기 바랍니다."),
    CHANGED_CAR_NUMBER_OR_MACHINE("CF-13235", "번호가 변경된 차량(건설기계)입니다. 확인 후 거래하시기 바랍니다."),
    CONSTRUCTION_MACHINE_REQUIRES_DATA_CORRECTION("CF-13236", "데이터 정정 요청이 필요한 건설기계입니다. 확인 후 거래하시기 바랍니다."),
    CAR_OWNER_ID_MISMATCH("CF-13237", "입력된 차량번호(등록번호)와 소유자 주민번호가 일치하지 않습니다. 확인 후 거래하시기 바랍니다."),
    SMS_VERIFICATION_CODE_MISMATCH("CF-13300", "SMS 인증번호가 일치하지 않습니다. 확인 후 거래하시기 바랍니다."),
    SECURITY_NUMBER_MISMATCH("CF-13301", "보안숫자가 일치하지 않습니다. 확인 후 거래하시기 바랍니다."),
    EMAIL_VERIFICATION_CODE_MISMATCH("CF-13302", "이메일 인증번호가 일치하지 않습니다. 확인 후 거래하시기 바랍니다."),
    AUTH_REQUEST_LIMIT_EXCEEDED("CF-13309", "인증 요청 횟수를 초과했습니다. 확인 후 거래하시기 바랍니다."),
    ISSUE_NUMBER_NOT_PROVIDED("CF-13310", "발급번호를 입력하지 않았습니다. 확인 후 거래하시기 바랍니다."),
    INVALID_ISSUE_NUMBER("CF-13311", "비정상적인 발급번호 입니다. 확인 후 거래하시기 바랍니다."),
    NON_EXISTENT_ISSUE_NUMBER("CF-13312", "없는 발급번호입니다. 확인 후 거래하시기 바랍니다."),
    ISSUE_NUMBER_FORMAT_ERROR("CF-13313", "발급번호 형식 오류입니다. 확인 후 거래하시기 바랍니다."),
    ISSUE_NUMBER_LENGTH_ERROR("CF-13314", "발급번호 자리수 오류입니다. 확인 후 거래하시기 바랍니다."),
    ISSUE_NUMBER_RELATED_ERROR("CF-13315", "발급번호 관련 오류입니다. 확인 후 거래하시기 바랍니다."),
    EXPIRED_ISSUE_NUMBER("CF-13316", "만료된 발급번호입니다. 확인 후 거래하시기 바랍니다."),
    CANNOT_VERIFY_DOCUMENT_ISSUED_BY_OWN_COMPANY("CF-13317", "자기 회사에서 발급한 문서는 원본 확인이 불가합니다. 확인 후 거래하시기 바랍니다."),
    ORIGINAL_VERIFICATION_ALLOWED_ONLY_AT_SUBMISSION("CF-13318", "원본 확인은 제출처에서만 가능합니다. 확인 후 거래하시기 바랍니다."),
    PREPAID_PAYMENT_NUMBER_NOT_PROVIDED("CF-13320", "선불전자지급수단 번호를 입력하지 않았습니다. 확인 후 거래하시기 바랍니다."),
    PREPAID_PAYMENT_NUMBER_ERROR("CF-13321", "선불전자지급수단 번호 오류입니다. 확인 후 거래하시기 바랍니다."),
    PREPAID_PAYMENT_NUMBER_ERROR_COUNT_EXCEEDED("CF-13322", "선불전자지급수단 번호 오류 횟수 초과입니다. 확인 후 거래하시기 바랍니다."),
    PREPAID_PAYMENT_NUMBER_FORMAT_ERROR("CF-13323", "선불전자지급수단 번호 형식 오류입니다. 확인 후 거래하시기 바랍니다."),
    PREPAID_PAYMENT_NUMBER_LENGTH_ERROR("CF-13324", "선불전자지급수단 번호 자리수 오류입니다. 확인 후 거래하시기 바랍니다"),
    PREPAID_PAYMENT_NUMBER_RELATED_ERROR("CF-13325", "선불전자지급수단 번호 관련 오류입니다. 확인 후 거래하시기 바랍니다."),
    PREPAID_PAYMENT_NUMBER_EXPIRED("CF-13326", "유효기간이 지난 선불전자지급수단 번호입니다. 확인 후 거래하시기 바랍니다."),
    PREPAID_PAYMENT_NUMBER_IN_PROGRESS("CF-13327", "처리중인 선불전자지급수단 번호입니다. 확인 후 거래하시기 바랍니다."),
    PREPAID_PAYMENT_INSUFFICIENT_BALANCE("CF-13328", "선불전자지급수단 번호의 잔액이 부족합니다. 확인 후 거래하시기 바랍니다."),
    PREPAID_PAYMENT_PASSWORD_NOT_PROVIDED("CF-13330", "선불전자지급수단 비밀번호를 입력하지 않았습니다. 확인 후 거래하시기 바랍니다."),
    PREPAID_PAYMENT_PASSWORD_ERROR("CF-13331", "선불전자지급수단 비밀번호 오류입니다. 확인 후 거래하시기 바랍니다."),
    PREPAID_PAYMENT_PASSWORD_ERROR_COUNT_EXCEEDED("CF-13332", "선불전자지급수단 비밀번호 오류 횟수 초과입니다. 확인 후 거래하시기 바랍니다."),
    PREPAID_PAYMENT_PASSWORD_FORMAT_ERROR("CF-13333", "선불전자지급수단 비밀번호 형식 오류입니다. 확인 후 거래하시기 바랍니다."),
    PREPAID_PAYMENT_PASSWORD_LENGTH_ERROR("CF-13334", "선불전자지급수단 비밀번호 자리수 오류입니다. 확인 후 거래하시기 바랍니다"),
    PREPAID_PAYMENT_PASSWORD_RELATED_ERROR("CF-13335", "선불전자지급수단 비밀번호 관련 오류입니다. 확인 후 거래하시기 바랍니다."),
    CASE_NOT_FOUND("CF-13338", "사건이 존재하지 않습니다. 확인 후 거래하시기 바랍니다."),
    NO_MATCHING_REGISTRATION_APPLICANT("CF-13339", "등기신청인 성명(등기권리자, 등기의무자, 신청인 중 1인) 또는 등기기록상의 소유자의 성명과 일치하는 신청사건이 없습니다. 확인 후 거래하시기 바랍니다."),
    EMAIL_NOT_PROVIDED("CF-13340", "이메일을 입력하지 않았습니다. 확인 후 거래하시기 바랍니다."),
    EMAIL_ALREADY_REGISTERED("CF-13341", "이미 등록된 이메일입니다. 다른 이메일 주소를 입력하시기 바랍니다."),
    EMAIL_FORMAT_ERROR("CF-13342", "이메일 형식 오류입니다. 확인 후 거래하시기 바랍니다."),
    INVALID_EMAIL("CF-13343", "잘못된 이메일입니다. 이메일 주소 확인 후 재시도 바랍니다."),
    ID_ALREADY_REGISTERED("CF-13349", "이미 등록된 아이디입니다. 다른 아이디를 입력하시기 바랍니다."),
    FILE_SIZE_EXCEEDED("CF-13350", "개별 파일의 용량이 초과되었습니다. 확인 후 거래하시기 바랍니다."),
    TOTAL_FILE_SIZE_EXCEEDED("CF-13351", "전체 파일 용량이 초과되었습니다. 확인 후 거래하시기 바랍니다."),
    FILE_COUNT_EXCEEDED("CF-13352", "첨부 파일 갯수가 초과되었습니다. 확인 후 거래하시기 바랍니다."),
    APPROVAL_NUMBER_NOT_PROVIDED("CF-13360", "승인번호를 입력하지 않았습니다. 확인 후 거래하시기 바랍니다."),
    INVALID_APPROVAL_NUMBER("CF-13361", "잘못된 승인번호입니다. 확인 후 거래하시기 바랍니다."),
    APPROVAL_NUMBER_FORMAT_ERROR("CF-13362", "승인번호 형식 오류입니다. 확인 후 거래하시기 바랍니다."),
    APPROVAL_NUMBER_LENGTH_ERROR("CF-13363", "승인번호 자리수 오류입니다. 확인 후 거래하시기 바랍니다."),
    APPROVAL_NUMBER_RELATED_ERROR("CF-13364", "승인번호 관련 오류입니다. 확인 후 거래하시기 바랍니다."),
    DONG_NOT_PROVIDED("CF-13400", "동을 입력하지 않으셨습니다. 확인 후 거래하시기 바랍니다."),
    NO_MATCHING_DONG("CF-13401", "일치하는 동이 없습니다. 확인 후 거래하시기 바랍니다."),
    NO_MATCHING_DONG_NUMBER("CF-13402", "일치하는 동번호가 없습니다. 확인 후 거래하시기 바랍니다."),
    HO_NOT_PROVIDED("CF-13403", "호를 입력하지 않으셨습니다. 확인 후 거래하시기 바랍니다."),
    NO_MATCHING_HO("CF-13404", "일치하는 호가 없습니다. 확인 후 거래하시기 바랍니다."),
    NO_MATCHING_HO_NUMBER("CF-13405", "일치하는 호번호가 없습니다. 확인 후 거래하시기 바랍니다."),
    NO_MATCHING_BUILDING_NUMBER("CF-13406", "일치하는 건물번호가 없습니다. 확인 후 거래하시기 바랍니다."),
    NO_MATCHING_JIBEON("CF-13407", "일치하는 지번이 없습니다. 확인 후 거래하시기 바랍니다."),
    NO_MATCHING_PROVINCE("CF-13408", "일치하는 시도가 없습니다. 확인 후 거래하시기 바랍니다."),
    PROVINCE_NOT_PROVIDED("CF-13409", "시도를 입력하지 않으셨습니다. 확인 후 거래하시기 바랍니다."),
    NO_MATCHING_CITY_DISTRICT("CF-13410", "일치하는 시군구가 없습니다. 확인 후 거래하시기 바랍니다."),
    CITY_DISTRICT_NOT_PROVIDED("CF-13411", "시군구를 입력하지 않으셨습니다. 확인 후 거래하시기 바랍니다."),
    NO_MATCHING_RI("CF-13412", "일치하는 리가 없습니다. 확인 후 거래하시기 바랍니다."),
    RI_NOT_PROVIDED("CF-13413", "리를 입력하지 않으셨습니다. 확인 후 거래하시기 바랍니다."),
    NO_OWNER_NAME_IN_BUILDING_LEDGER("CF-13414", "소유자명이 존재하지 않는 건축물대장입니다."),
    CALCULATION_DETAILS_NOT_GENERATED("CF-13500", "산출내역이 생성되지 않았습니다. 확인 후 거래하시기 바랍니다."),
    CHILD_ALREADY_REGISTERED("CF-13501", "기 등록된 자녀입니다. 확인 후 등록하시기 바랍니다."),
    NO_REGISTERABLE_CHILD("CF-13502", "등록가능한 자녀가 없습니다."),
    REPLY_ALREADY_REGISTERED("CF-13600", "이미 등록된 답글입니다. 확인 후 이용하시기 바랍니다."),
    NO_REAL_ESTATE_MATCHING_CODE("CF-13700", "입력한 발행코드와 일치하는 부동산이 없습니다.");

    private String code;
    private String message;
    private String extraMessage;

    private EasyCodefMessageConstant(String code, String message) {
        this.code = code;
        this.message = message;
    }

    public String getCode() {
        return code;
    }

    public String getMessage() {
        return message;
    }

    public void setExtraMessage(String extraMessage) {
        this.extraMessage = extraMessage;
    }

    public String getExtraMessage() {
        return extraMessage;
    }
}
